CREATE TABLE DEPT(
DNO VARCHAR2(3) CONSTRAINT DNO_UNQ_Cons UNIQUE
CONSTRAINT D_LikeDNO_Cons CHECK(DNO Like 'D%'),
DNAME VARCHAR2(10) CONSTRAINT DNAME_UNQ_Cons UNIQUE,
LOCATION VARCHAR2(9) CONSTRAINT VALID_LOC_Cons CHECK(LOCATION IN ('BNG','MNG','MUB','HYD','CHN')) 
);

CREATE TABLE EMP(
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9) CONSTRAINT JOB_CHK_Cons CHECK(JOB in ('CLRK','MGR','A.MGR','GM','CEO')),
MGRID NUMBER(4) CONSTRAINT MGR_FK_EMP_NO_Cons REFERENCES EMP,
DATE_BIRTH DATE,
SAL NUMBER(7,2) CONSTRAINT SAL_20K_MORE_Cons CHECK(SAL>20000),
COMM NUMBER(7,2) DEFAULT 1000,
DEPTNO VARCHAR2(3) CONSTRAINT DEPTNO_FK_DEPT_Cons REFERENCES DEPT(DNO) ON DELETE CASCADE,
DATE_JOIN DATE,
CONSTRAINT DB_LESS_DBJOIN_Cons CHECK(DATE_BIRTH<DATE_JOIN)
);

CREATE TABLE PROJ(
DNO VARCHAR2(3) CONSTRAINT DNO_FK_DEPT_Cons REFERENCES DEPT(DNO) NOT NULL,
PRJ_NO VARCHAR2(5)  CONSTRAINT PRJ_LIKEPRJNO_Cons CHECK(PRJ_NO LIKE 'P%') NOT NULL,
PRJ_NAME VARCHAR2(10),
PRJ_CREDIT NUMBER(2) CONSTRAINT PRJ_CREDIT_RANGE_Cons CHECK(PRJ_CREDIT BETWEEN 1 AND 10),
STRT_DATE DATE,
END_DATE DATE,
CONSTRAINT ENDDATE_GRT_STRT_Cons CHECK(END_DATE>STRT_DATE)
);

ALTER TABLE PROJ
ADD CONSTRAINT PK_DNO_PRJNO PRIMARY KEY(DNO,PRJ_NO);

ALTER TABLE EMP
ADD PRJ_ID VARCHAR2(8);

ALTER TABLE EMP
  2  ADD CONSTRAINT EMP_PRJ_FK FOREIGN KEY(DEPTNO, PRJ_ID) REFERENCES PROJ(DNO, PRJ_NO);

ALTER TABLE EMP
ADD CONSTRAINT VALID_EMPNO_Cons CHECK(EMPNO>100);

ALTER TABLE DEPT ADD DEPT_BUDGET NUMBER(7);

ALTER TABLE PROJ ADD PRJ_FUND NUMBER(7);