
ALTER TABLE PROJ
ADD CONSTRAINT PK_DNO_PRJNO PRIMARY KEY(DNO,PRJ_NO);

ALTER TABLE EMP
ADD PRJ_ID VARCHAR2(8);

ALTER TABLE EMP ADD CONSTRAINT EMP_PRJ_FK FOREIGN KEY(DEPTNO, PRJ_ID) REFERENCES PROJ(DNO, PRJ_NO) ;

ALTER TABLE EMP
ADD CONSTRAINT VALID_EMPNO_Cons CHECK(EMPNO>100);

ALTER TABLE DEPT ADD DEPT_BUDGET NUMBER(7);

ALTER TABLE PROJ ADD PRJ_FUND NUMBER(7);